"""Add business column to business table

Revision ID: 0072043823ee
Revises: ee7ca9a58794
Create Date: 2021-01-04 06:38:39.209606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0072043823ee'
down_revision = 'ee7ca9a58794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('business_owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'businesses', 'users', ['business_owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_column('businesses', 'business_owner_id')
    # ### end Alembic commands ###
