""" Add role column to customer table

Revision ID: 0f4ac59c654f
Revises: 2467df465df8
Create Date: 2020-12-30 22:36:08.570267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f4ac59c654f'
down_revision = '2467df465df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'role_id')
    # ### end Alembic commands ###
