""" Change customer-order relationship to one to many

Revision ID: ee7ca9a58794
Revises: 0f4ac59c654f
Create Date: 2020-12-30 23:05:32.908138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee7ca9a58794'
down_revision = '0f4ac59c654f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_orders')
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'customer_id')
    op.create_table('customer_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name='customer_orders_customer_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='customer_orders_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='customer_orders_pkey')
    )
    # ### end Alembic commands ###
